# AI Workshop #2 Part B
# AI with Python - Data Preparation

## 2.5. Introduction

In the previous workshop,we have already studied supervised as well as unsupervised machine learning algorithms. 

These algorithms require formatted data to start the training process. We must prepare 
or format data in a certain way so that it can be supplied as an input to ML algorithms.

This workshop will focus on the data preparation for machine learning algorithms.

## 2.6. Preprocessing the Data

In our daily life, we deal with lots of data but this data is in raw form. To provide the data as the input of machine learning algorithms, we need to convert it into a meaningful data. 

That is where data preprocessing comes into picture. 

In other simple words, we can say that before providing the data to the machine learning algorithms we need to preprocess the data.

## 2.7. Data Preprocessing Steps

Follow these steps to preprocess the data in Python:

### Step 1: Importing the useful packages ###

If we are using Python then this would be the first step for converting the data into a certain format, i.e., preprocessing. It can be done as follows:

In [3]:
import numpy as np
from sklearn import preprocessing

<img src="./Fig/note2.png" width = "" height = "" alt="Supervised ML" align=left />

Here we have used the following two packages:
- **NumPy**: Basically NumPy is a general purpose array-processing package designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without sacrificing too much speed for small multi-dimensional arrays.
- **Sklearn.preprocessing**: This package provides many common utility functions and transformer classes to change raw feature vectors into a representation that is more suitable for machine learning algorithms.

### Step 2: Defining sample data ###

After importing the packages, we need to define some sample data so that we can apply preprocessing techniques on that data. 

For example, we now define the following sample data:

In [4]:
input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                      [0.5, -7.9, 5.6],
                      [5.9, 2.3, -5.8]])

To display the array, use standard print() function:

In [8]:
print("Array Input_data is:\n", input_data)

Array Input_data is:
 [[ 2.1 -1.9  5.5]
 [-1.5  2.4  3.5]
 [ 0.5 -7.9  5.6]
 [ 5.9  2.3 -5.8]]


### Step3: Applying preprocessing technique ### 

In this step, we need to apply any of the preprocessing techniques. 

The following section describes the data preprocessing techniques.

## 2.8 Techniques for Data Preprocessing ##

The techniques for data preprocessing are described below:

### Binarization ###

This is the preprocessing technique which is used when we need to convert our numerical 
values into Boolean values. We can use an inbuilt method to binarize the input data say 
by using 0.5 as the threshold value in the following way:

In [9]:
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(input_data)

Check the binarized data array:

In [10]:
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


<img src="./Fig/note.png" width = "" height = "" alt="Supervised ML" align=left />

**Note**:
Binarization is a simple but important data-processing procedure, especially in neural network training. In many neural networks/Deep networks problem, we only need the binary data as input vectors instead of the real number, e.g. car plate number recognition, signature recognition, etc. In these case, binary information of 2D pixel arrary are used as input vectors. 

In our example, after running the above code we will get the following output, all the values above 0.5(threshold value) would be converted to 1 and all the values below 0.5 would be converted to 0.

### Mean Removal ###

It is another very common preprocessing technique that is used in machine learning. 

Basically it is used to eliminate the mean from feature vector so that every feature is 
centered on zero. We can also remove the bias from the features in the feature vector. 

For applying mean removal preprocessing technique on the sample data, we can write the 
Python code shown below. The code will display the Mean and Standard deviation of the 
input data:

In [11]:
print("Mean =", input_data.mean(axis=0))
print("Std deviation = ", input_data.std(axis=0))

Mean = [ 1.75  -1.275  2.2  ]
Std deviation =  [2.71431391 4.20022321 4.69414529]


Now, the code below will remove the **Mean** and **Standard deviation** of the input data:

In [12]:
data_scaled = preprocessing.scale(input_data)
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

Mean = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Std deviation = [1. 1. 1.]


### Scaling ###

It is another data preprocessing technique that is used to scale the feature vectors. 

Scaling of feature vectors is needed because the values of every feature can vary between many random values. 

In other words we can say that scaling is important because we do not want any feature to be synthetically large or small. 

With the help of the following Python code, we can do the scaling of our input data, i.e., feature vector:

#### Min max Scaling ####

In [13]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print ("\nMin max scaled data:\n", data_scaled_minmax)


Min max scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


<img src="./Fig/workshop.png" width = "" height = "" alt="Supervised ML" align=left />

### Workshop 2.1 - Data Scaling ###

Scaling is an important data-preprocessing technique in many AI problem, especially for the data processing for ANN/Deep Network. 

Using weather forecast as example, discuss how Scaling Method is used for weather prediction with various input vectors such as Temperature, Air Pressure, Relative Humidity, Wind Speed and Director, etc. 



### Workshop 2.1 Answer: ###

Data scaling maps raw feature values into a comparable range so that features with larger magnitudes do not dominate distance-based or gradient-based models. In the weather dataset, `Pressure` (~1000) and `precipitation` (0–20) are on very different scales, while `temp_max` and `temp_min` are closer in range.

I applied MinMax scaling to the numeric weather features so each column is transformed to [0, 1]. This preserves the relative order of values within each feature and makes it easier to compare and combine features during preprocessing. Scaling is especially useful before clustering, KNN, neural networks, and any algorithm sensitive to feature magnitude.



In [2]:
# Step 1: Importing the useful packagesimport pandas as pd
import numpy as np
import pandas as pd
from sklearn import preprocessing

# Step 2: Read the csv by using the pandas.
input_datapd = pd.read_csv('./weather.csv')
print(input_datapd.head())
# Acorrding to the output below, we see that they are different types of data.
# If we use these data to train the weather prediction system directly, then features with larger numerical values dominate predictions, while those with smaller values will be ignored.
# That is why we will use the scaling method to let all the data fall within a relative fair weight range.

subset = input_datapd[['Pressure','precipitation','temp_max','temp_min','wind speed ','wind direction']]
print(subset.head())
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(subset)
print ("\nMin max scaled data:\n", data_scaled_minmax)
#Now we scal all the data about the number so that any feature will not be synthetically large or small.

       date  Pressure  precipitation  temp_max  temp_min  wind speed   \
0  1/1/2012      1090            0.0      12.8       5.0          4.7   
1  2/1/2012      1060           10.9      10.6       2.8          4.5   
2  3/1/2012      1012            0.8      11.7       7.2          2.3   
3  4/1/2012      1095           20.3      12.2       5.6          4.7   
4  5/1/2012      1041            1.3       8.9       2.8          6.1   

   wind direction  weather  
0              35  drizzle  
1             112     rain  
2             138     rain  
3             146     rain  
4             233     rain  
   Pressure  precipitation  temp_max  temp_min  wind speed   wind direction
0      1090            0.0      12.8       5.0          4.7              35
1      1060           10.9      10.6       2.8          4.5             112
2      1012            0.8      11.7       7.2          2.3             138
3      1095           20.3      12.2       5.6          4.7             146
4      

### Normalization ###

**Normalization** is another data preprocessing technique that is used to modify the feature vectors. 

Such kind of modification is necessary to measure the feature vectors on a common scale. 

Followings are two types of normalization which can be used in machine learning:

#### L1 Normalization ####

It is also referred to as **Least Absolute Deviations**. 

This kind of normalization modifies the values so that the sum of the absolute values is always up to 1 in each row. 

It can be implemented on the input data with the help of the following Python code:

In [15]:
# Normalize data
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')

In [16]:
print("\nL1 normalized data:\n", data_normalized_l1)


L1 normalized data:
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]


#### L2 Normalization ####

It is also referred to as **least squares normalization**. 

This kind of normalization modifies the values so that the sum of the squares is always up to 1 in each row. 

It can be implemented on the input data with the help of the following Python code:

In [17]:
# Normalize data
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')

In [18]:
print("\nL2 normalized data:\n", data_normalized_l2)


L2 normalized data:
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]


<img src="./Fig/workshop.png" width = "" height = "" alt="Supervised ML" align=left />

### Workshop 2.2 - Normalization Techniques ###

Compare standard, L1 and L2 normalization, please discuss what are there main difference in terms of data preprocessing. And discuss (with examples) what are the problem domains (data types) that best fit for each normalization scheme. 

### Workshop 3.2 Answer: ###


## 2.9 Labeling the Data ##

We already know that data in a certain format is necessary for machine learning 
algorithms. 

Another important requirement is that the data must be labelled properly before sending it as the input of machine learning algorithms. 

For example, if we talk about classification, there are lot of labels on the data. Those labels are in the form of words, numbers, etc. 

Functions related to machine learning in sklearn expect that the data must have number labels. 

Hence, if the data is in other form then it must be converted to numbers. This process of transforming the word labels into numerical form is called **label encoding**.

### Label encoding steps ###

Follow these steps for encoding the data labels in Python:

#### Step1: Importing the useful packages ####

If we are using Python then this would be first step for converting the data into certain 
format, i.e., preprocessing. It can be done as follows:

In [19]:
import numpy as np
from sklearn import preprocessing

#### Step 2: Defining sample labels ####

After importing the packages, we need to define some sample labels so that we can create 
and train the label encoder. 

We will now define the following sample labels:

In [20]:
# Sample input labels
input_labels = ['red','black','red','green','black','yellow','white']

In [21]:
input_labels

['red', 'black', 'red', 'green', 'black', 'yellow', 'white']

#### Step 3: Creating & training of label encoder object ####

In this step, we need to create the label encoder and train it. 

The following Python code will help in doing this:

In [22]:
# Creating the label encoder
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

LabelEncoder()

#### Step4: Checking the performance by encoding random ordered list ####

This step can be used to check the performance by encoding the random ordered list. 

Following Python code can be written to do the same:

In [23]:
# encoding a set of labels
test_labels = ['green','red','black']
encoded_values = encoder.transform(test_labels)

Check the test_labels:

In [24]:
print("\nLabels =", test_labels)


Labels = ['green', 'red', 'black']


Now, we can get the list of encoded values i.e. word labels converted to numbers as 
follows:

In [25]:
print("Encoded values =", list(encoded_values))

Encoded values = [np.int64(1), np.int64(2), np.int64(0)]


#### Step 5: Checking the performance by decoding a random set of numbers: ####

This step can be used to check the performance by decoding the random set of numbers. 

Following Python code can be written to do the same:

In [26]:
# decoding a set of values
encoded_values = [3,0,4,1]
decoded_list = encoder.inverse_transform(encoded_values)

Check the encoded values:

In [27]:
print("\nEncoded values =", encoded_values)


Encoded values = [3, 0, 4, 1]


Now, decoded values would get printed as follows:

In [28]:
print("\nDecoded labels =", list(decoded_list))


Decoded labels = [np.str_('white'), np.str_('black'), np.str_('yellow'), np.str_('green')]


<img src="./Fig/workshop.png" width = "" height = "" alt="Supervised ML" align=left />

### Workshop 2.3 - Data Labeling ###

In many AI classification problem, we using come across input (vectors) which are NON number in nature. 

1) Please give THREE examples of such AI problem and describe HOW it can be handled by using **Data Labeling** method. 

2) Discuss the pros and cons of such method. 

### Workshop 2.3 Answer: ###


## 2.10 Labeled v/s Unlabeled Data ##

Unlabeled data mainly consists of the samples of natural or human-created object that can 
easily be obtained from the world. They include, audio, video, photos, news articles, etc. 

On the other hand, labeled data takes a set of unlabeled data and augments each piece of 
that unlabeled data with some tag or label or class that is meaningful. For example, if we have a photo then the label can be put based on the content of the photo, i.e., it is photo of a boy or girl or animal or anything else. Labeling the data needs human expertise or judgment about a given piece of unlabeled data. 

There are many scenarios where unlabeled data is plentiful and easily obtained but labeled data often requires a human/expert to annotate. Semi-supervised learning attempts to combine labeled and unlabeled data to build better models.

<img src="./Fig/workshop.png" width = "" height = "" alt="Supervised ML" align=left />

### Workshop 2.4 ###

Data preprocessing is a critical procedure in many real world machine learning and AI problem. Using weather forecast as example, various data preprocessing such as data normalization, scaling and labeling are needed before the time-series weather information can be used for network training and testing. 

Use the time series weather data of Seattle (weather.csv) provided in this workshop as the time-series raw data for data preprocessing:
1) Describe and explain the nature of data in each attribute of the time series records.
2) Discuss what kind of data preprocessing methods are needed for each attribute. 
3) How about missing record and incorrect data, how can we fix such problems.
4) Write Python program to implement the data processing method. 

Hint:
The **normal** range and condition of each weather attribute are:
1. Air Pressure 900 - 1200
2. Precipitation 0 - 300
3. Temperature -50 - 50
4. Max >= Min Temp
5. Wind Speed (Grade) 0 - 10
6. Wind Direction 0 - 360

### Workshop 2.4 Answer: ###

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
# Load the data
input_data = pd.read_csv('./weather.csv')
print(input_data.head(),"\n")

# Convert the date column to datetime type with specified format
input_data['date'] = pd.to_datetime(input_data['date'], format='%d/%m/%Y')

# Handling incorrect data
# Clip the Pressure column to the range [900, 1200]
input_data['Pressure'] = input_data['Pressure'].clip(900, 1200)

# Clip the precipitation column to the range [0, 300]
input_data['precipitation'] = input_data['precipitation'].clip(0, 300)

# If temp_max < temp_min, swap them
input_data['temp_max'], input_data['temp_min'] = np.where(input_data['temp_max'] < input_data['temp_min'], (input_data['temp_min'], input_data['temp_max']), (input_data['temp_max'], input_data['temp_min']))

# Clip the wind speed column to the range [0, 10], using the correct column name with extra space
input_data['wind speed '] = input_data['wind speed '].clip(0, 10)

# Convert wind direction values outside 0 - 360 to the equivalent angle within the range
input_data['wind direction'] = input_data['wind direction'] % 360

# Normalize numerical columns using Min - Max Scaling
scaler = preprocessing.MinMaxScaler()
columns_to_scale = ['Pressure', 'precipitation', 'temp_max', 'temp_min', 'wind speed ', 'wind direction']
input_data[columns_to_scale] = scaler.fit_transform(input_data[columns_to_scale])

# Use label encoding for the weather column
le = preprocessing.LabelEncoder()
input_data['weather'] = le.fit_transform(input_data['weather'])

print("The Data After Preprocessing\n" , input_data)

       date  Pressure  precipitation  temp_max  temp_min  wind speed   \
0  1/1/2012      1090            0.0      12.8       5.0          4.7   
1  2/1/2012      1060           10.9      10.6       2.8          4.5   
2  3/1/2012      1012            0.8      11.7       7.2          2.3   
3  4/1/2012      1095           20.3      12.2       5.6          4.7   
4  5/1/2012      1041            1.3       8.9       2.8          6.1   

   wind direction  weather  
0              35  drizzle  
1             112     rain  
2             138     rain  
3             146     rain  
4             233     rain   

The Data After Preprocessing
            date  Pressure  precipitation  temp_max  temp_min  wind speed   \
0    2012-01-01  0.633333       0.000000  0.018663  0.476378         0.47   
1    2012-01-02  0.533333       0.194991  0.015811  0.389764         0.45   
2    2012-01-03  0.373333       0.014311  0.017237  0.562992         0.23   
3    2012-01-04  0.650000       0.363148  0.017